# This file was generated by GoReleaser. DO NOT EDIT.
cask "clawker" do
  version "0.7.8"

  on_macos do
    on_intel do
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_darwin_amd64.tar.gz"
      sha256 "ae47f8378c89bd00069252cef208db732f5d995d68800b5ccf35cecf39cb3168"
    end
    on_arm do
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_darwin_arm64.tar.gz"
      sha256 "6f0023a8574b8929a9861e3d0deb173799e85fc151fdd647baffa6e9bf8af6ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_linux_amd64.tar.gz"
      sha256 "07f90951ba264b3b3f4611591a8297c9892338cd1d618ae9563182a43cdbc479"
    end
    on_arm do
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_linux_arm64.tar.gz"
      sha256 "170a1131668744c7f2d0d4b6ab2e841ca1bfa1c2e0f1d401e5c87eddf6fb0f74"
    end
  end

  name "clawker"
  desc "Development containers for AI coding agents"
  homepage "https://github.com/schmitthub/clawker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clawker"

  postflight do
    if OS.mac?
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clawker"]
    end
  end

  # No zap stanza required

end
