# This file was generated by GoReleaser. DO NOT EDIT.
cask "clawker" do
  version "2026.9.1"

  on_macos do
    on_intel do
      sha256 "f37f80fb94b5de802561b03556b150012ed2f43793eb74e4bb1f721604a45211"
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3125eec1219e0d8cf682ecd041cd3daf3f59b4116798d71640cdb5ed5dc92c2"
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2adeb2629633ccb51c6dd399941be6056d271ea71ad50f8d24a3d5d738b0f859"
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ed092d040b9805d8aaf71d3a3d5b4e9eda4d2313e90606b5e8bd6cffc362d1a"
      url "https://github.com/schmitthub/clawker/releases/download/v#{version}/clawker_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clawker"
  desc "Development containers for AI coding agents"
  homepage "https://github.com/schmitthub/clawker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clawker"

  postflight do
    if OS.mac?
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clawker"]
    end
  end

  # No zap stanza required

end
