# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclaw-docker" do
  name "openclaw-docker"
  desc "CLI for building custom OpenClaw Dockerfiles"
  homepage "https://github.com/schmitthub/openclaw-docker"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openclaw-docker"

  on_macos do
    on_intel do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_darwin_amd64.tar.gz"
      sha256 "ca15718dad75f70f8e88a7b43acd6422abde63805d9319a58537a7dceea60e10"
    end
    on_arm do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_darwin_arm64.tar.gz"
      sha256 "a9130feb23159251f632cb9a5e492390930fcb8be45dd43cf38c242f04323c3b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_linux_amd64.tar.gz"
      sha256 "27e6f77d14ceaa6774d21228a579c2838df43ecb927a73518528978548b5268d"
    end
    on_arm do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_linux_arm64.tar.gz"
      sha256 "2f4828dc34531d83e41913f26ad17cfd5ff7d9a83d6ebd87dfe7f1650008d29b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openclaw-docker"]
    end
  end

  # No zap stanza required
end
