# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclaw-docker" do
  name "openclaw-docker"
  desc "CLI for building custom OpenClaw Dockerfiles"
  homepage "https://github.com/schmitthub/openclaw-docker"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openclaw-docker"

  on_macos do
    on_intel do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_darwin_amd64.tar.gz"
      sha256 "d32fbd331928211b1df54453eb2ce81b204cf8fa0d2fdaf56af982517ba16e14"
    end
    on_arm do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_darwin_arm64.tar.gz"
      sha256 "a89871a1815b2b58e7086824a44b502ac571654f21cfae463a7e695919debfa7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_linux_amd64.tar.gz"
      sha256 "ecc94e240ab5a50f1e3c7ee250b412283eb9f4fdfd4f7448d018ee061b69088b"
    end
    on_arm do
      url "https://github.com/schmitthub/openclaw-docker/releases/download/v#{version}/openclaw-docker_#{version}_linux_arm64.tar.gz"
      sha256 "8b767646b203e7f098d85a5f9b351736c6aa235dda941716f1e89cd233599e51"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openclaw-docker"]
    end
  end

  # No zap stanza required
end
