# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawker < Formula
  desc "Development containers for AI coding agents"
  homepage "https://github.com/schmitthub/clawker"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.2/clawker_0.3.2_darwin_amd64.tar.gz"
      sha256 "0394aae4bb2c41aebe678cdf47ab7e20677a2e684e74deecff3de59ea21356ac"

      define_method(:install) do
        bin.install "clawker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.2/clawker_0.3.2_darwin_arm64.tar.gz"
      sha256 "5cbfe0329ea7d24c2532126fa8b4c17dc2c953f5f0c337cc003fcb84280787b7"

      define_method(:install) do
        bin.install "clawker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.2/clawker_0.3.2_linux_amd64.tar.gz"
      sha256 "4ee95c05ea440b6af8c6b97cb7fd3423cd547f3227a3264273c2b17a5464566e"
      define_method(:install) do
        bin.install "clawker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.2/clawker_0.3.2_linux_arm64.tar.gz"
      sha256 "cf7c9033e815138c0f41d17f20779ebd57235dcc7351a4b4c8dfb062d05e6a72"
      define_method(:install) do
        bin.install "clawker"
      end
    end
  end
end
