# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawker < Formula
  desc "Development containers for AI coding agents"
  homepage "https://github.com/schmitthub/clawker"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.1/clawker_0.3.1_darwin_amd64.tar.gz"
      sha256 "20c97c6c07f24feaff3b1b36380c762ba82053cde7b5ee63e4609bb471672513"

      define_method(:install) do
        bin.install "clawker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.1/clawker_0.3.1_darwin_arm64.tar.gz"
      sha256 "af02e8a907851ab11cfaa6f536a5dd4fcc28bb29ccd5bff55a30ee7a0e130745"

      define_method(:install) do
        bin.install "clawker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.1/clawker_0.3.1_linux_amd64.tar.gz"
      sha256 "cbb553b96e25092d8dc65b0135c444ecb4511e990dba5624e63269e5cedd1f21"
      define_method(:install) do
        bin.install "clawker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schmitthub/clawker/releases/download/v0.3.1/clawker_0.3.1_linux_arm64.tar.gz"
      sha256 "2e1805b7fdb5598a2664b9c27ee0d632f9ca1befcbe0de7330c259ae76de7c94"
      define_method(:install) do
        bin.install "clawker"
      end
    end
  end
end
