# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawker < Formula
  desc "Development containers for AI coding agents"
  homepage "https://github.com/schmitthub/clawker"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schmitthub/clawker/releases/download/v0.4.0/clawker_0.4.0_darwin_amd64.tar.gz"
      sha256 "66757227807ab4c84b909122308aaaeebc3608d4f2afe425b6c562fada24b18b"

      define_method(:install) do
        bin.install "clawker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schmitthub/clawker/releases/download/v0.4.0/clawker_0.4.0_darwin_arm64.tar.gz"
      sha256 "194c724b459e1a5aaa013a05357f2d01784d6c40c79641904336fae658488b9a"

      define_method(:install) do
        bin.install "clawker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schmitthub/clawker/releases/download/v0.4.0/clawker_0.4.0_linux_amd64.tar.gz"
      sha256 "09145693c08b951ca1fa979dd052ef8bc9f9b5c109090ae7ef9c3eeccf4bc69e"
      define_method(:install) do
        bin.install "clawker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schmitthub/clawker/releases/download/v0.4.0/clawker_0.4.0_linux_arm64.tar.gz"
      sha256 "b816709dd9f8f98a5af32d5427d7d8ad7566676ac21b8187d04485cf90b11fe7"
      define_method(:install) do
        bin.install "clawker"
      end
    end
  end
end
